baseURL = "https://gremlex.carlabs.ai/"
languageCode = "en-us"
relativeURLs = true
uglyURLs = true

title = "Gremlex"

theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
editURL = "https://github.com/Revmaker/gremlex_site"

[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github repo"
identifier = "github"
url = "https://github.com/Revmaker/gremlex"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Hex.pm package"
identifier = "hex"
url = "https://hex.pm/packages/gremlex"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Gremlex Documentation"
identifier = "gremlexdoc"
url = "https://hexdocs.pm/gremlex/api-reference.html"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30